### ISSUE TITLE
MSAL module issue when enabling Entra ID role

### ISSUE THREAD

**Issue by pawelpvl** [DanielChronlund/DCToolbox#43]
Hi,

I have not found such an issue on the issues page. Could you please help with the issue below?

![image](https://github.com/DanielChronlund/DCToolbox/assets/88552314/3b1dcbb6-119a-4c3e-a777-e62ce28cfa31)

**Comment by vuwdalderman** [comment]
I think this is because the RedirectUri parameter on the Get-MsalToken is set to "urn:ietf:wg:oauth:2.0:oob" which has been deprecated. The RedirectUri can be http://localhost like this:

```
# Get token for MS Graph by prompting for MFA.
$MsResponse = Get-MsalToken -Scopes @('https://graph.microsoft.com/.default') -ClientId "14d82eec-204b-4c2f-b7e8-296a70dab67e" **-RedirectUri "http://localhost" -**Authority 'https://login.microsoftonline.com/common' -Interactive -ExtraQueryParameters @{claims = '{"access_token" : {"amr": { "values": ["mfa"] }}}' }
```

**Comment by pawelpvl** [comment]
Thank you :) the issue can be closed I think
